### ISSUE TITLE
Add to iTunes resets watched status

### ISSUE THREAD

**Issue by joewarmelink** [ccjensen/PlexMediaTagger#10]
I currently have Plex running on the same machine as an iTunes library.  I use an AppleTV and I prefer watching movies at home thru Apple's Home Sharing, and not using the Plex server directly, since the AppleTV doesn't have a Plex app for it.

We put movies files into a folder indexed by Plex.  Nightly, I have a script run using PlexMediaTagger to update the movies and add anything new to my iTunes library.  I use the following command:

plexmediatagger.py -b --tag -f --add-to-itunes -q

As I understand, this would update all the movies in my Plex library with the correct content, and then add any new movies to my iTunes library if they are missing.

The issue is that every night when this happens, it seems to have "reset" my iTunes library and removes the watched/unwatched flag from each movie.  So now it's very difficult to tell what movies I have and haven't watched.

According to the documentation, --add-to-itunes should only add the movie if it's not in the library.  Why is it resetting the watched status on all my other movies?  I believe this to be an issue.

**Comment by ccjensen** [comment]
Hi,

Could you try removing the "-f" from the command you run? It causes all actions to be run again even if they have been performed before. I believe this is likely why the watch status is being reset.

**Comment by joewarmelink** [comment]
Oh man!  Thanks so much!  I will try that and let you know.

**Comment by joewarmelink** [comment]
You're correct!  Sorry about that. I believe the issue I was originally having was that I have a handful of corrupt movies in my library.  Without the -f flag, it would hit the corrupt file and then stop processing everything.  I wanted it to continue on failures, so I added the -f option to keep it going, but then apparently that screwed up my watched statuses.  Thanks much!  It was easy enough to just clean up corrupt files from my library.

**Comment by ccjensen** [comment]
no problem; just glad we got it sorted!
