### ISSUE TITLE
'artist' content type is not supported

### ISSUE THREAD

**Issue by Protectator** [ccjensen/PlexMediaTagger#12]
Hi !

I tried using your script on my library. I'm trying it on a Music Library, but the process seems to end as soon as it starts. Here is the output when I launched it on my collection :

```
Section to process $2
Processing sections
Processing section 1/1 : 'Protectator' =========================================
 'artist' content type is not supported
Section 'Protectator' processed
Processing sections completed
========================= Plex Media Tagger Completed ==========================
Parts processed:                0
Execution Duration:             0:00:03
========================== Items Processed Statistics ==========================
Number of items:                0
-------------------------------------------------------
Number of Movies:               0
Number of TV Episodes:          0
-------------------------------------------------------
Total Duration:
Average Duration:
-------------------------------------------------------
Total TV Episodes Duration:
Average TV Episode Duration:
-------------------------------------------------------
Total Movies Duration:
Average Movie Duration:
```
And the script ends without doing anything. This is a section of music files, btw. Is there any way to correct this behaviour ?

**Comment by ccjensen** [comment]
Hi,

I only use it for video files, so apologies but it's not going to work for music without quite a bit of work from someone. Feel free to fork and send me a push request if you end up taking it on yourself :)

**Comment by Protectator** [comment]
Oh sorry, didn't see it was mentioned that this wasn't compatible with audio libraries. I might take a look at it if I have enough time.
