### ISSUE TITLE
HTTP Error 500: Internal Server Error

### ISSUE THREAD

**Issue by ArnaudFeld** [ccjensen/PlexMediaTagger#17]
Hi,

when is want so start PlexMediaTagger i get:

HTTP Error 500: Internal Server Error

Starting PMT in Verbose-Mode i get no more Information.

Plex-Server-Version 1.9.7.4460

If you need more Information just contact me :)

**Comment by ccjensen** [comment]
what is your invocation?

**Comment by ccjensen** [comment]
and that used to work, or are you just now trying to use it for the first time?

**Comment by ArnaudFeld** [comment]
This works for a long time for me

**Comment by ccjensen** [comment]
Just tried things at home and it still works fine for me. My server is reporting version 1.13 . Is there a reason you are running an older version? might make sense for sanity to have it run the latest

**Comment by ArnaudFeld** [comment]
Sorry Plex told me that it was the Last Version.
i Have The Version Version 1.13.0.5023 on my Private Server now (updated manually).
Reboot after the Update also done too.

But Still the Same error...

**Comment by ccjensen** [comment]
so script hasn't changed, and up until now you hadn't updated your server since it last worked, right? Implies maybe something changed locally on your machine? some sort of firewall settings changed?

**Comment by ArnaudFeld** [comment]
yes that is correct.

i tried it on an second machine (of a friend) get the same error (Plex-Server-Version 1.13)
No Firewall settings or similar was changed.

**Comment by ccjensen** [comment]
just trying to figure out what could be different with your set up. you a plex pass member?

**Comment by ArnaudFeld** [comment]
yes i'm plex pass member

**Comment by ArnaudFeld** [comment]
Could it be the Python Version?

```
python -V                                                                                                        
Python 2.7.14
```

**Comment by ccjensen** [comment]
I'm not a plex pass member, so that could be it. My python version is "Python 2.7.10" so that is close enough that that is unlikely to be the problem.

**Comment by ccjensen** [comment]
maybe try with a double `v`, so:
`python /Volumes/Thor/PlexMediaTagger/plexmediatagger.py --username=[myPLEXUSER] --password=[myPASSWORD] -tvvo`

**Comment by ccjensen** [comment]
actually I am seeing this now too, which makes it easier to work on

**Comment by ArnaudFeld** [comment]
This i get with the suggest invocation:

`============================================================================= Plex Media Tagger Started =============================================================================
 Authenticating user '[PLEXUSER]' with plex.tv...
 HTTP Error 500: Internal Server Error`

**Comment by ArnaudFeld** [comment]
Yes now Worms for me too 😁👍

Thanks
