### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gelsas** [ccjensen/PlexMediaTagger#19]
Hello, 

I am not sure if I understand this programm correctly. I am quite new to all of this.

I am searching for a way to save the metadata from plex in the media file itself, because some movies I needed to match manually and it would be great if I somehow could save that information to the media file so if I ever need to setup a server again it will match correctly automatically.

Is that what your programm does ? (Sorry for the stupid question)

**Comment by ccjensen** [comment]
Yes, that is what it does but only works on macOS and mp4/m4v files
