### ISSUE TITLE
could not connect to server

### ISSUE THREAD

**Issue by Tigrecito** [ccjensen/PlexMediaTagger#7]
as already posted to plex forum, I can´t get the script to run properly. I´m using the current pms 0.9.11.6:

python plexmediatagger.py -t -d 

WARNING, RUNNING IN 'DRY RUN MODE'. NO ACTUAL CHANGES WILL BE MADE
========================== Plex Media Tagger Started ===========================
Connecting to PMS at localhost:32400
Could not connect to server localhost:32400

**Comment by Tigrecito** [comment]
ok, thanks.. I´m back again and ready ;)

**Comment by ccjensen** [comment]
hi, I have made a branch with my proposed changes. could you give them a go and see if they work. the main difference is I've added the ability to provide a username and password when running the script, which will then connect to plex.tv and get an authentication token to use to talk to the PMS.
Let me know if you aren't sure how to get the code that is on the branch.

**Comment by ccjensen** [comment]
patel4prez on the forums tested these changes and they seemed to work, so I have now put them in to the program. Look for the new options --username, --password and --interactive-password.
Please file a new issue if these don't work for you.
